window.BetterPromptConfig = {
  ui: {
    title: "Better Prompt",
    subtitle: "Делаем идеальный промпт за вас",
    inputTitle: "Входной промпт",
    inputMeta: "Исходный",
    inputLabel: "Вставьте текст",
    inputPlaceholder:
      "Например: придумай 10 идей для постов о стартапе в области ИИ...",
    outputTitle: "Обновлённый промпт",
    outputMeta: "Улучшенный",
    outputHint: "Нажмите на текст, чтобы скопировать.",
    scoreTitle: "Оценка промпта",
    scoreLabels: {
      efficiency: "Эффективность",
      length: "Длина",
      clarity: "Ясность",
      structure: "Структура",
    },
    pasteLabel: "Вставить",
    confirmLabel: "Подтвердить",
    copyLabel: "Скопировать",
    telegramLabel: "Бот в Telegram",
  },
  api: {
    endpoint: "/api/improve",
  },
  telegramUrl: "https://t.me/parseetestbot_bot",
  statusStages: ["Собираем", "Смотрим", "Ищем", "Обрабатываем", "Склеиваем"],
  memeLines: [
    "Проверяем смысловые узлы.",
    "Сжимаем шум, усиливаем сигнал.",
    "Выравниваем тон и формат.",
    "Легкий тюнинг без магии.",
    "Собираем лучшую версию.",
  ],
  idle: {
    defaultStatus: "",
    defaultMeme: "Никаких лишних слов.",
    pasted: "Промпт вставлен. Готовы улучшать.",
    emptyClipboard: "Буфер пустой. Вставьте текст вручную.",
    clipboardError: "Не удалось прочитать буфер. Вставьте текст вручную.",
    noPrompt: "Сначала добавьте промпт.",
    done: "Готово. Можно копировать.",
    error: "Не удалось улучшить промпт. Попробуйте ещё раз.",
    errorOutput: "Ошибка обработки. Проверьте подключение и повторите попытку.",
  },
  loading: {
    dotIntervalMs: 450,
    stageIntervalMs: 1400,
    memeIntervalMs: 1600,
    totalDelayMs: 3200,
  },
  toast: {
    copied: "Скопировано",
  },
};
