window.BetterPromptConfig = {
  ui: {
    title: "Better Prompt",
    subtitle: "Prompt workspace",
    heroKicker: "Prompt lab",
    heroTitle: "Create something special today",
    heroSubtitle: "Собери сильный запрос за минуты и сохрани стиль.",
    projectsTitle: "Projects",
    collectionsTitle: "Collections",
    projectName: "Your first project",
    inputTitle: "Входной промпт",
    inputMeta: "RAW",
    inputLabel: "Вставьте текст",
    inputPlaceholder:
      "Например: придумай 10 идей для постов о стартапе в области ИИ...",
    outputTitle: "Обновлённый промпт",
    outputMeta: "V2",
    outputHint: "Нажмите на текст, чтобы скопировать.",
    pasteLabel: "Paste",
    confirmLabel: "Подтвердить",
    copyLabel: "Copy to clipboard",
    telegramLabel: "Telegram bot",
  },
  telegramUrl: "https://t.me/your_bot",
  statusStages: ["Собираем", "Смотрим", "Ищем", "Обрабатываем", "Склеиваем"],
  memeLines: [
    "Проверяем смысловые узлы.",
    "Сжимаем шум, усиливаем сигнал.",
    "Выравниваем тон и формат.",
    "Легкий тюнинг без магии.",
    "Собираем лучшую версию.",
  ],
  idle: {
    defaultStatus: "Готов. Ждём промпт.",
    defaultMeme: "Никаких лишних слов.",
    pasted: "Промпт вставлен. Готовы улучшать.",
    emptyClipboard: "Буфер пустой. Вставьте текст вручную.",
    clipboardError: "Не удалось прочитать буфер. Вставьте текст вручную.",
    noPrompt: "Сначала добавьте промпт.",
    done: "Готово. Можно копировать.",
  },
  loading: {
    dotIntervalMs: 450,
    stageIntervalMs: 1400,
    memeIntervalMs: 1600,
    totalDelayMs: 3200,
  },
  output: {
    templateLines: [
      "ROLE:",
      "Ты — экспертный ассистент, который превращает запросы в точные решения.",
      "",
      "CONTEXT:",
      "Пользователь дал исходный запрос. Твоя задача — дать лучший возможный ответ.",
      "",
      "INPUT:",
      "{{input}}",
      "",
      "INSTRUCTIONS:",
      "1. Переформулируй запрос в 1-2 предложения для проверки понимания.",
      "2. Если чего-то не хватает, задай до 3 уточняющих вопросов.",
      "3. Дай структурированный ответ: краткий план → основной ответ → краткие выводы.",
      "4. Соблюдай лаконичный, деловой тон без лишних украшений.",
      "",
      "OUTPUT FORMAT:",
      "- Заголовок",
      "- План (3-7 пунктов)",
      "- Основной ответ",
      "- Итоги",
      "",
      "META: Better Prompt · {{timestamp}}",
    ],
    locale: "ru-RU",
    timestampOptions: {
      dateStyle: "short",
      timeStyle: "short",
    },
  },
  toast: {
    copied: "Скопировано",
  },
};
